# Generated by Django 6.0.3 on 2026-04-30 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=200, unique=True, verbose_name='name')),
                ('image', models.CharField(blank=True, default='', max_length=500, verbose_name='image')),
                ('container_id', models.CharField(blank=True, default='', max_length=200, verbose_name='container id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('removed', 'Removed')], default='pending', max_length=20, verbose_name='status')),
                ('backend_port', models.IntegerField(blank=True, null=True, verbose_name='backend port')),
                ('frontend_port', models.IntegerField(blank=True, null=True, verbose_name='frontend port')),
                ('health_status', models.CharField(blank=True, default='', max_length=100, verbose_name='health status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='last health check')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='config')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_instances', to=settings.AUTH_USER_MODEL)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_instances', to='generation.generationjob')),
            ],
            options={
                'verbose_name': 'Container Instance',
                'verbose_name_plural': 'Container Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='action id')),
                ('action_type', models.CharField(choices=[('build', 'Build'), ('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart'), ('remove', 'Remove'), ('logs', 'Logs'), ('health', 'Health')], db_index=True, max_length=20, verbose_name='action type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='progress percent')),
                ('output', models.TextField(blank=True, default='', verbose_name='output')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='exit code')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_actions', to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='runtime.containerinstance')),
            ],
            options={
                'verbose_name': 'Container Action',
                'verbose_name_plural': 'Container Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_port', models.IntegerField(unique=True, verbose_name='backend port')),
                ('frontend_port', models.IntegerField(unique=True, verbose_name='frontend port')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_allocation', to='runtime.containerinstance')),
            ],
            options={
                'verbose_name': 'Port Allocation',
                'verbose_name_plural': 'Port Allocations',
            },
        ),
    ]
