# Generated by Django 6.0.3 on 2026-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('version', models.CharField(default='v1', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=200)),
                ('benchmark', models.CharField(db_index=True, max_length=64)),
                ('score', models.FloatField()),
                ('source', models.CharField(choices=[('seed', 'Seed fixture'), ('openrouter', 'OpenRouter'), ('huggingface', 'Hugging Face'), ('manual', 'Manual entry')], default='seed', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['model_id', 'benchmark'],
                'indexes': [models.Index(fields=['benchmark', '-score'], name='rankings_be_benchma_00ec94_idx')],
                'unique_together': {('model_id', 'benchmark')},
            },
        ),
    ]
