# Generated by Django 6.0.3 on 2026-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. openai/gpt-4o",
                        max_length=300,
                        unique=True,
                        verbose_name="OpenRouter model ID",
                    ),
                ),
                (
                    "canonical_slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="URL-safe version: openai_gpt-4o",
                        max_length=300,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="provider"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=300, verbose_name="display name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="free")),
                (
                    "context_window",
                    models.IntegerField(
                        default=0, verbose_name="context window (tokens)"
                    ),
                ),
                (
                    "max_output_tokens",
                    models.IntegerField(default=0, verbose_name="max output tokens"),
                ),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_streaming", models.BooleanField(default=False)),
                ("supports_json_mode", models.BooleanField(default=False)),
                (
                    "input_price_per_token",
                    models.FloatField(default=0.0, verbose_name="input price/token"),
                ),
                (
                    "output_price_per_token",
                    models.FloatField(default=0.0, verbose_name="output price/token"),
                ),
                (
                    "cost_efficiency",
                    models.FloatField(
                        default=0.0, verbose_name="cost efficiency (0-1)"
                    ),
                ),
                (
                    "capabilities_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="raw OpenRouter payload"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="structured metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["provider", "model_name"],
            },
        ),
    ]
