"""Post-render hook registry.

A hook is ``Callable[[Path, *, manifest, context], None]``. Register new hooks
with :func:`register_hook` or by decorating with ``@register_hook("name")``.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any

Hook = Callable[..., None]
HOOKS: dict[str, Hook] = {}


def register_hook(name: str) -> Callable[[Hook], Hook]:
    def _deco(fn: Hook) -> Hook:
        HOOKS[name] = fn
        return fn
    return _deco


@register_hook("write_sanitize_icons_script")
def _write_sanitize_icons_script(dest: Path, *, manifest: Any, context: Any) -> None:
    """Drop the lucide-react sanitizer cjs script into frontend/scripts/."""
    target = dest / "frontend" / "scripts" / "sanitize-icons.cjs"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_SANITIZE_ICONS_SCRIPT)


_SANITIZE_ICONS_SCRIPT = r"""// Auto-generated by llm_lab scaffolding.
// LLM-produced App.jsx frequently imports icon names that don't exist in
// lucide-react (e.g. "Toggle2"). Rollup aborts the build on these. We
// rewrite each `import { ... } from 'lucide-react'` statement to keep only
// names that are real exports, and alias the rest to HelpCircle so any JSX
// references still resolve at runtime.
const fs = require('fs');
const path = require('path');

const FILE = path.resolve(__dirname, '..', 'src', 'App.jsx');
const FALLBACK = 'HelpCircle';

let lucide;
try {
  lucide = require('lucide-react');
} catch (err) {
  console.error('sanitize-icons: lucide-react not installed, skipping');
  process.exit(0);
}
const valid = new Set(Object.keys(lucide));
if (!valid.has(FALLBACK)) {
  console.error('sanitize-icons: HelpCircle not exported, skipping');
  process.exit(0);
}

let src;
try {
  src = fs.readFileSync(FILE, 'utf8');
} catch (err) {
  console.error('sanitize-icons: App.jsx not found, skipping');
  process.exit(0);
}

const IMPORT_RE = /import\s*\{([^}]*)\}\s*from\s*['"]lucide-react['"]\s*;?/g;
const aliases = new Set();
let changed = false;

src = src.replace(IMPORT_RE, (_full, body) => {
  const kept = [];
  const items = body.split(',').map((s) => s.trim()).filter(Boolean);
  for (const item of items) {
    const parts = item.split(/\s+as\s+/).map((s) => s.trim());
    const orig = parts[0];
    const local = parts[1] || orig;
    if (valid.has(orig)) {
      kept.push(item);
    } else {
      aliases.add(local);
      changed = true;
      console.error('sanitize-icons: removing unknown icon', orig);
    }
  }
  return `import { ${kept.join(', ')} } from 'lucide-react';`;
});

if (changed) {
  if (!new RegExp(`\\b${FALLBACK}\\b[^']*from\\s+['\"]lucide-react`).test(src)) {
    src = `import { ${FALLBACK} as __FallbackIcon__ } from 'lucide-react';\n` + src;
  } else {
    src = `const __FallbackIcon__ = ${FALLBACK};\n` + src;
  }
  const decls = [...aliases].map((n) => `const ${n} = __FallbackIcon__;`).join('\n');
  const lastImport = src.match(/(^import[^;]+;\s*$)/gm);
  if (lastImport && lastImport.length) {
    const idx = src.lastIndexOf(lastImport[lastImport.length - 1]) + lastImport[lastImport.length - 1].length;
    src = src.slice(0, idx) + '\n' + decls + '\n' + src.slice(idx);
  } else {
    src = decls + '\n' + src;
  }
  fs.writeFileSync(FILE, src);
  console.error('sanitize-icons: rewrote App.jsx, replaced', aliases.size, 'unknown icons');
}
"""
