# Generated by Django 6.0.5 on 2026-05-19 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter')], max_length=32)),
                ('encrypted_secret', models.TextField()),
                ('key_prefix', models.CharField(blank=True, default='', max_length=12)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_status', models.CharField(choices=[('unvalidated', 'Not yet validated'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('rate_limited', 'Rate limited'), ('network_error', 'Network error')], default='unvalidated', max_length=32)),
                ('last_validation_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
