# Generated by Django 6.0.5 on 2026-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapicredential',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('huggingface', 'Hugging Face')], max_length=32),
        ),
    ]
