# Generated by Django 6.0.3 on 2026-04-30 16:44

import django.db.models.deletion
import llm_lab.reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_add_query_indexes'),
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.SlugField(default=llm_lab.reports.models._new_report_id, max_length=64, unique=True, verbose_name='public id')),
                ('report_type', models.CharField(choices=[('model_analysis', 'Model analysis'), ('template_comparison', 'Template comparison'), ('tool_analysis', 'Tool analysis'), ('generation_analytics', 'Generation analytics'), ('comprehensive', 'Comprehensive')], max_length=40, verbose_name='type')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='config')),
                ('report_data', models.JSONField(blank=True, default=dict, verbose_name='report data')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='summary')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='progress %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('analysis_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analysis.analysistask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='generation.generationjob')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx')],
            },
        ),
    ]
