# Generated by Django 6.0.3 on 2026-04-05 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("generation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "analyzer_name",
                    models.CharField(
                        help_text="Analyzer identifier, e.g. 'bandit', 'eslint'",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "default_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default configuration for this analyzer",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_code",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Inline code for analysis: {'backend': '...', 'frontend': '...'}",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which analyzers to run and their settings",
                    ),
                ),
                (
                    "results_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Aggregated findings count by severity, overall score, etc.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_tasks",
                        to="generation.generationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analyzer_type",
                    models.CharField(
                        choices=[
                            ("static", "Static Analysis"),
                            ("dynamic", "Dynamic Analysis"),
                            ("performance", "Performance Analysis"),
                            ("ai", "AI Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "analyzer_name",
                    models.CharField(
                        help_text="Specific tool name, e.g. 'bandit', 'eslint', 'zap', 'llm_review'",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed summary: score, metrics, tool version, etc.",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysistask",
                    ),
                ),
            ],
            options={
                "ordering": ["analyzer_type", "analyzer_name"],
                "unique_together": {("task", "analyzer_name")},
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("quality", "Code Quality"),
                            ("performance", "Performance"),
                            ("style", "Style"),
                            ("best_practice", "Best Practice"),
                            ("accessibility", "Accessibility"),
                            ("seo", "SEO"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "suggestion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Recommended fix or improvement",
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("line_number", models.PositiveIntegerField(blank=True, null=True)),
                ("column_number", models.PositiveIntegerField(blank=True, null=True)),
                ("code_snippet", models.TextField(blank=True, default="")),
                (
                    "rule_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tool-specific rule identifier, e.g. 'B105', 'no-unused-vars'",
                        max_length=200,
                    ),
                ),
                ("tool_specific_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="analysis.analysisresult",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(severity="critical", then=0),
                        models.When(severity="high", then=1),
                        models.When(severity="medium", then=2),
                        models.When(severity="low", then=3),
                        models.When(severity="info", then=4),
                        default=5,
                        output_field=models.IntegerField(),
                    ),
                    "-created_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["severity"], name="analysis_fi_severit_569d07_idx"
                    ),
                    models.Index(
                        fields=["category"], name="analysis_fi_categor_4e7081_idx"
                    ),
                    models.Index(
                        fields=["result", "severity"],
                        name="analysis_fi_result__657353_idx",
                    ),
                ],
            },
        ),
    ]
