# Generated by Django 6.0.3 on 2026-04-06 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
        ("generation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["task", "status"], name="analysis_an_task_id_115ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["task", "analyzer_name"], name="analysis_an_task_id_7b3c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysistask",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="analysis_an_created_a218df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysistask",
            index=models.Index(fields=["status"], name="analysis_an_status_0f7535_idx"),
        ),
    ]
