# Generated by Django 6.0.3 on 2026-04-03 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='category')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('backend_requirements', models.JSONField(blank=True, default=list, verbose_name='backend requirements')),
                ('frontend_requirements', models.JSONField(blank=True, default=list, verbose_name='frontend requirements')),
                ('admin_requirements', models.JSONField(blank=True, default=list, verbose_name='admin requirements')),
                ('api_endpoints', models.JSONField(blank=True, default=list, verbose_name='API endpoints')),
                ('data_model', models.JSONField(blank=True, default=dict, verbose_name='data model')),
                ('is_default', models.BooleanField(default=False, verbose_name='system default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_requirement_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Requirement Template',
                'verbose_name_plural': 'App Requirement Templates',
                'ordering': ['-is_default', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='batch name')),
                ('mode', models.CharField(max_length=20, verbose_name='generation mode')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('total_jobs', models.PositiveIntegerField(default=0, verbose_name='total jobs')),
                ('completed_jobs', models.PositiveIntegerField(default=0, verbose_name='completed jobs')),
                ('failed_jobs', models.PositiveIntegerField(default=0, verbose_name='failed jobs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation Batch',
                'verbose_name_plural': 'Generation Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('custom', 'Custom'), ('scaffolding', 'Scaffolding'), ('copilot', 'Copilot')], max_length=20, verbose_name='generation mode')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('custom_system_prompt', models.TextField(blank=True, default='', verbose_name='system prompt')),
                ('custom_user_prompt', models.TextField(blank=True, default='', verbose_name='user prompt')),
                ('temperature', models.FloatField(default=0.3, verbose_name='temperature')),
                ('max_tokens', models.PositiveIntegerField(default=32000, verbose_name='max tokens')),
                ('copilot_description', models.TextField(blank=True, default='', verbose_name='copilot description')),
                ('copilot_max_iterations', models.PositiveIntegerField(default=5, verbose_name='max iterations')),
                ('copilot_current_iteration', models.PositiveIntegerField(default=0, verbose_name='current iteration')),
                ('copilot_use_open_source', models.BooleanField(default=True, verbose_name='prefer open-source models')),
                ('app_directory', models.CharField(blank=True, default='', max_length=500, verbose_name='app directory')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Generated code, token usage, cost, etc.', verbose_name='result data')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Token usage, cost, timing', verbose_name='metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='generation.apprequirementtemplate')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='generation.generationbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='llm_models.llmmodel')),
            ],
            options={
                'verbose_name': 'Generation Job',
                'verbose_name_plural': 'Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='e.g. "backend", "frontend", "copilot_iter_1"', max_length=50, verbose_name='stage')),
                ('request_payload', models.JSONField(default=dict, verbose_name='request payload')),
                ('response_payload', models.JSONField(default=dict, verbose_name='response payload')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='completion tokens')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='estimated cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='generation.generationjob')),
            ],
            options={
                'verbose_name': 'Generation Artifact',
                'verbose_name_plural': 'Generation Artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('stage', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], max_length=20, verbose_name='stage')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=20, verbose_name='role')),
                ('content', models.TextField(verbose_name='template content')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_default', models.BooleanField(default=False, verbose_name='system default')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['-is_default', 'stage', 'role', 'name'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='backend_prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backend_jobs', to='generation.prompttemplate'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='frontend_prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_jobs', to='generation.prompttemplate'),
        ),
        migrations.CreateModel(
            name='ScaffoldingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('tech_stack', models.JSONField(blank=True, default=dict, help_text='e.g. {"frontend": "React 18", "backend": "Flask 3.x"}', verbose_name='tech stack')),
                ('template_archive', models.FileField(blank=True, help_text='.tar.gz of the scaffolding directory', upload_to='scaffolding/', verbose_name='template archive')),
                ('substitution_vars', models.JSONField(blank=True, default=list, help_text='List of {{var}} placeholders available in the template', verbose_name='substitution variables')),
                ('is_default', models.BooleanField(default=False, verbose_name='system default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scaffolding_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scaffolding Template',
                'verbose_name_plural': 'Scaffolding Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='scaffolding_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='generation.scaffoldingtemplate'),
        ),
        migrations.CreateModel(
            name='CopilotIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.PositiveIntegerField(verbose_name='iteration')),
                ('action', models.CharField(choices=[('generate', 'Generate'), ('build', 'Build'), ('fix', 'Fix'), ('validate', 'Validate')], max_length=20, verbose_name='action')),
                ('llm_request', models.JSONField(blank=True, default=dict, verbose_name='LLM request')),
                ('llm_response', models.TextField(blank=True, default='', verbose_name='LLM response')),
                ('build_output', models.TextField(blank=True, default='', verbose_name='build output')),
                ('build_success', models.BooleanField(default=False, verbose_name='build succeeded')),
                ('errors_detected', models.JSONField(blank=True, default=list, verbose_name='errors detected')),
                ('fix_applied', models.TextField(blank=True, default='', verbose_name='fix applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_iterations', to='generation.generationjob')),
            ],
            options={
                'verbose_name': 'Copilot Iteration',
                'verbose_name_plural': 'Copilot Iterations',
                'ordering': ['job', 'iteration_number'],
                'unique_together': {('job', 'iteration_number')},
            },
        ),
    ]
