# Generated by Django 6.0.3 on 2026-04-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
